### ISSUE TITLE
Too Much DEBUG Data for Old CodeView format

### ISSUE THREAD

**Issue by etcimon** [DigitalMars/optlink#14]
This follows the following thread:

https://github.com/rejectedsoftware/dub/issues/307#issuecomment-42314883

You forgot to initialize CV_4_TYPE correctly, I'm not sure how I would do it. Could you look into this?

Thanks!

*edit: I factored a bundle of modifications and those in cvindex.asm were not necessary, so I found that `CV_4_TYPE` is not to blame. The problem lies with qsortlin.asm only*

**Comment by denis-sh** [comment]
@WalterBright, could you have a look at this issue and proposed pull? This is a real PITA as single file compilation generally ~10 times slower.
